[tool.poetry]
name = "knowledgehub"
version = "0.1.0"
description = ""
authors = ["Atticus Zhou <1831768457@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
