name: Run Python Script and Update README

on:
  push:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: 'main'
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configuring git credentials
        run: |
          git config --global user.email "1831768457@qq.com"
          git config --global user.name "Atticuszz"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run the script
        run: python scripts/main.py

      - name: Commit README changes
        run: |
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update README.md automatically" && git push)